// ============================================================
// src/services/pdf/pdfService.js
// Core PDF engine using pdfkit
// ============================================================

'use strict';

const PDFDocument = require('pdfkit');
const fs          = require('fs');
const path        = require('path');
const { createLogger } = require('../../utils/logger');
const log = createLogger('pdfService');

// Create a new PDF document
function createDocument(options = {}) {
    return new PDFDocument({
        size:    'A4',
        margin:  50,
        info:    {
            Title:    options.title    || 'MaalSaathi Document',
            Author:   'MaalSaathi',
            Subject:  options.subject  || '',
            Keywords: 'maalsaathi, truck, logistics',
        },
        ...options,
    });
}

// Save PDF to /tmp directory (Render compatible)
async function saveToFile(doc, filename) {
    return new Promise((resolve, reject) => {
        const filePath = path.join('/tmp', filename);
        const stream   = fs.createWriteStream(filePath);

        doc.pipe(stream);
        doc.end();

        stream.on('finish', () => {
            log.info(`PDF saved: ${filePath}`);
            resolve(filePath);
        });
        stream.on('error', (err) => {
            log.error(`PDF save error: ${err.message}`);
            reject(err);
        });
    });
}

// Add MaalSaathi header to PDF
function addHeader(doc, title) {
    doc.fontSize(22)
       .fillColor('#2563eb')
       .text('🚛 MaalSaathi', { align: 'center' });

    doc.fontSize(14)
       .fillColor('#666')
       .text(title, { align: 'center' });

    doc.moveTo(50, doc.y + 10)
       .lineTo(545, doc.y + 10)
       .stroke('#e5e7eb');

    doc.moveDown(2);
}

// Add footer
function addFooter(doc) {
    doc.fontSize(9)
       .fillColor('#999')
       .text(
           'Generated by MaalSaathi | maalsaathi.in',
           50, doc.page.height - 50,
           { align: 'center', width: 495 }
       );
}

module.exports = { createDocument, saveToFile, addHeader, addFooter };
